### ISSUE TITLE
panic happens when configured

### ISSUE THREAD

**Issue by TerraSkye** [devopsfaith/krakend-httpsecure#1]
im trying to configure the config according to the following docs
this documentation https://github.com/devopsfaith/krakend-documentation/blob/85d586a05a36a24abf894677c3521eeeff1d41b9/endpoints/security.md 

```
        "github_com/devopsfaith/krakend-httpsecure": {
            "allowed_hosts": [],
            "ssl_proxy_headers": {},
            "sts_seconds": "300",
            "frame_deny": false,
            "sts_include_subdomains": false
        },
```
with this in mind i configured the config like above which results in a panic. 

see the trace 
```
panic: interface conversion: interface {} is string, not int

goroutine 1 [running]:
github.com/devopsfaith/krakend-ce/vendor/github.com/devopsfaith/krakend-httpsecure.getInt64(...)
        /go/src/github.com/devopsfaith/krakend-ce/vendor/github.com/devopsfaith/krakend-httpsecure/httpsecure.go:74
github.com/devopsfaith/krakend-ce/vendor/github.com/devopsfaith/krakend-httpsecure.ConfigGetter(0xc0007019b0, 0xc00071a800, 0x5)
        /go/src/github.com/devopsfaith/krakend-ce/vendor/github.com/devopsfaith/krakend-httpsecure/httpsecure.go:32 +0x790
github.com/devopsfaith/krakend-ce/vendor/github.com/devopsfaith/krakend-httpsecure/gin.Register(0xc0007019b0, 0xc00034c6c0, 0x1, 0x1)
```

what i tried voor the `sts_seconds` is  
- integer  (300)
- string ("300") 

they both raise a panic

**Comment by kpacha** [comment]
you're right, the documentation is wrong.

it's also weird integers aren't parsed either. I'm improving the parsing process
